# Generated by Django 2.0.2 on 2018-02-24 19:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20180224_1913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'file', 'verbose_name_plural': 'files'},
        ),
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='document',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='datetime'),
        ),
        migrations.AlterField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='folder.Folder', verbose_name='folder'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(default=None, max_length=128, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(default='file', max_length=128, verbose_name='file'),
        ),
    ]
