# Generated by Django 2.0.2 on 2018-02-28 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vk_api_wrapper', '0007_auto_20180225_1315'),
        ('document', '0004_auto_20180225_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='vk_doc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vk_api_wrapper.DocAttachment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='id_owner',
            field=models.IntegerField(null=True, verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='document',
            name='id_source',
            field=models.IntegerField(null=True, verbose_name='source'),
        ),
    ]
