# Generated by Django 2.0.2 on 2018-03-05 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_auto_20180228_2013'),
        ('document', '0005_auto_20180228_1635'),
    ]

    operations = [
    ]
