# Generated by Django 2.0.2 on 2018-03-10 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_auto_20180228_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='document',
            name='id_owner',
        ),
        migrations.RemoveField(
            model_name='document',
            name='id_source',
        ),
    ]
