# Generated by Django 2.0.2 on 2018-03-13 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_auto_20180310_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='document.Document')),
            ],
        ),
    ]
