# Generated by Django 2.0.2 on 2018-03-31 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0007_documentdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
