# Generated by Django 2.0.2 on 2018-04-14 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0010_document_id_elastic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='id_elastic',
            field=models.CharField(default='1', max_length=1024),
        ),
    ]
