# Generated by Django 2.0.2 on 2018-04-19 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0010_document_id_elastic'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
