# Generated by Django 2.0.2 on 2018-04-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0011_document_is_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created',
            field=models.DateTimeField(verbose_name='datetime'),
        ),
    ]
