# Generated by Django 2.0.2 on 2018-02-24 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=128, verbose_name='название')),
                ('type', models.CharField(default='папка', max_length=128, verbose_name='папка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='отправитель')),
                ('root', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='folder.Folder', verbose_name='родитель')),
            ],
            options={
                'verbose_name': 'папка',
                'verbose_name_plural': 'папки',
            },
        ),
    ]
