# Generated by Django 2.0.2 on 2018-02-24 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0002_auto_20180224_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='root',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='folder.Folder', verbose_name='родитель'),
        ),
    ]
