# Generated by Django 2.0.2 on 2018-02-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0005_auto_20180224_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='type',
            field=models.CharField(choices=[('folder', 'folder'), ('chat', 'chat')], default='folder', max_length=128, verbose_name='type of folder'),
        ),
    ]
