# Generated by Django 2.0.2 on 2018-03-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0007_auto_20180306_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='type',
            field=models.CharField(choices=[('folder', 'folder'), ('chat', 'chat'), ('root', 'root'), ('sorted', 'sorted')], default='folder', max_length=128, verbose_name='type of folder'),
        ),
    ]
