# Generated by Django 2.0.2 on 2018-03-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0008_auto_20180306_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='type',
            field=models.CharField(choices=[('folder', 'folder'), ('chat', 'chat'), ('root', 'root'), ('sorted', 'sorted'), ('favorite', 'favorite')], default='folder', max_length=128, verbose_name='type of folder'),
        ),
    ]
