# Generated by Django 2.0.2 on 2018-03-10 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0010_chatfolder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatfolder',
            name='vk_dialog',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vk_api_wrapper.VkDialog'),
        ),
    ]
