# Generated by Django 2.0.2 on 2018-03-25 10:31

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0012_auto_20180325_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='root',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_set', to='folder.Folder', verbose_name='root'),
        ),
    ]
