# Generated by Django 2.0.2 on 2018-04-13 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0012_folder_typeforelasticsearchpleasedonttouchme'),
        ('folder', '0014_auto_20180326_1839'),
    ]

    operations = [
    ]
