# Generated by Django 2.0.2 on 2018-04-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder', '0015_merge_20180413_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='icon',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
