# Generated by Django 2.0.2 on 2018-02-25 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vk_api_wrapper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vkdialogslist',
            old_name='user_id',
            new_name='user',
        ),
    ]
