# Generated by Django 2.0.2 on 2018-02-25 10:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vk_api_wrapper', '0003_vkdialog'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkdialog',
            name='chat_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='vkdialog',
            unique_together={('user', 'chat_id')},
        ),
    ]
