# Generated by Django 2.0.2 on 2018-02-25 13:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vk_api_wrapper', '0006_docattachment_vkmessageslist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='docattachment',
            unique_together={('user', 'vk_id', 'vk_owner_id')},
        ),
    ]
