# Generated by Django 2.0.2 on 2018-03-10 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vk_api_wrapper', '0008_docattachment_vk_dialog'),
    ]

    operations = [
        migrations.CreateModel(
            name='VkDocsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.BigIntegerField(blank=True, default=None, null=True)),
                ('prev_count', models.BigIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vkdocslist',
            unique_together={('user', 'owner_id')},
        ),
    ]
