# Generated by Django 2.0.2 on 2018-03-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_api_wrapper', '0009_auto_20180310_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docattachment',
            name='date',
            field=models.BigIntegerField(),
        ),
    ]
