# Generated by Django 2.0.2 on 2018-03-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_api_wrapper', '0010_auto_20180310_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docattachment',
            name='ext',
            field=models.CharField(max_length=63),
        ),
    ]
