# Generated by Django 2.0.2 on 2018-04-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vk_api_wrapper', '0012_vkdialog_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkdialog',
            name='photo',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
