# Generated by Django 2.0.2 on 2018-02-25 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180224_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vk_id',
            field=models.IntegerField(default=0, verbose_name='vk_id'),
            preserve_default=False,
        ),
    ]
