# Generated by Django 2.0.2 on 2018-02-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_vk_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vk_id',
            field=models.IntegerField(null=True, verbose_name='vk_id'),
        ),
    ]
