# Generated by Django 2.0.2 on 2018-03-05 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180228_1618'),
        ('core', '0004_auto_20180227_2126'),
    ]

    operations = [
    ]
